server.port=8082
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/idreamdb?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
course.service.url=${COURSE_SERVICE_URL:http://localhost:8081}
management.endpoints.web.exposure.include=health,info
